"""Add interpretation tables

Revision ID: d06d3a66d9cf
Revises: 7c706cc3657d
Create Date: 2024-11-22 14:26:06.242449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06d3a66d9cf'
down_revision = '7c706cc3657d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream_interpretations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interpretation_text', sa.Text(), nullable=False),
    sa.Column('interpretation_type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dream_interpretations_dreams',
    sa.Column('interpretation_id', sa.Integer(), nullable=False),
    sa.Column('dream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dream_journals.id'], ),
    sa.ForeignKeyConstraint(['interpretation_id'], ['dream_interpretations.id'], ),
    sa.PrimaryKeyConstraint('interpretation_id', 'dream_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dream_interpretations_dreams')
    op.drop_table('dream_interpretations')
    # ### end Alembic commands ###
